# Site
name: "Mostafa Shahverdy's Blog"
title: "Mostafa Shahverdy's Blog"
description: "Personal Ideas and Book Recommendations"
logo: 'assets/images/avatar.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: http://shahverd.ir
google_analytics: 'G-W45CGLG1MQ'
disqus: 'shahverd'
mailchimp-list: 'https://shahverd.us21.list-manage.com/subscribe/post?u=28289d8bc2ef28921a8742873&amp;id=c4d2b27722&amp;f_id=00bc58e1f0'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mostafa:
    name: "Mostafa Shahverdy"
    display_name: "Mostafa Shahverdy"
    gravatar: fea237cc76e4670d56e75b81f2f3e66ae06a07c85a029f381325af87fc3856b4
    email: shahverdy.m+personal_blog@gmail.com
    web: https://www.shahverd.ir
    twitter: https://twitter.com/shahverd
    description: "Husband, Father, Automating engineer, 🚀 SaaS Founder ☁️ AWS DevOps ❤️ Python 💻 AI / Machine Learning"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
